# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('neighborhood', models.TextField()),
                ('gate_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_addition_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ikinciElApp.Brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ikinciElApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_addition_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_addition', models.DateTimeField(default=django.utils.timezone.now)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ikinciElApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_sell_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sell_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/pictures/', verbose_name='profile picture')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.NullBooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ikinciElApp.Address')),
                ('basket_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ikinciElApp.Basket')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product_sell_log',
            name='user_purchaser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_processing',
            name='user_purchaser_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alici_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_processing',
            name='user_vendor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satici_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_addition_log',
            name='user_vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ikinciElApp.Product'),
        ),
    ]
