# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ikinciElApp', '0003_basket_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
