# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikinciElApp', '0008_auto_20171212_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_addition_log',
            name='product_addition',
        ),
    ]
