# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ikinciElApp', '0009_remove_product_addition_log_product_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_addition_log',
            name='product_addition',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 12, 45, 53, 896986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_sell_log',
            name='product_sell_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 12, 45, 53, 897490, tzinfo=utc)),
        ),
    ]
