# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ikinciElApp', '0010_auto_20171212_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_addition_log',
            name='product_addition',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 10, 41, 27, 233560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product_sell_log',
            name='product_sell_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 10, 41, 27, 234063, tzinfo=utc)),
        ),
    ]
